### PR TITLE
openstack: fix conversion for block volumes

### LINKED ISSUE #710: Fix openstack qcow2 snapshot conversion for volumeMode: Block
1. The destination path is not correctly set
2. Copy data between block devices

### PR DESCRIPTION
**Pull request by bennyz**
fix #710

### CODE REVIEW

File: cmd/image-converter/image-converter.go [hunk 1]
```diff
@@ -57,21 +72,5 @@ func convert(srcVolPath, dstVolPath, sourceFormat, targetFormat string) error {
 		return err
 	}
 
-	// Replace /mnt/disk.img with /output/disk.img
-	cmd = exec.Command(
```
Comment (liranr23) [inline cmd/image-converter/image-converter.go:61]: why mv or cp can't work while qemu-img convert does?

Comment (bennyz) [reply cmd/image-converter/image-converter.go:61]: it works only for files, for block volumes you need to copy the content of the device

although now that I think about it may actually make sense to keep the `mv` for files, because it should be much faster

Comment (ahadas) [reply cmd/image-converter/image-converter.go:61]: > although now that I think about it may actually make sense to keep the `mv` for files, because it should be much faster

are you sure qemu-img doesn't have this optimization? AFAIU vdsm always invokes qemu-img for this and I find it surprising if it could have been optimized

Comment (bennyz) [reply cmd/image-converter/image-converter.go:61]: I suspect that's because of the other parameters vdsm uses, I'd be very surprised if qemu-img will do what `mv` does

**Review by liranr23 — APPROVED** [review]

File: cmd/image-converter/image-converter.go [hunk 2]
```diff
@@ -25,13 +27,39 @@ func main() {
...
+		}
+	} else {
+		// Use mv for files as its faster than qemu-img convert
+		cmd := exec.Command("mv", dstVolPath, srcVolPath)
+		err := cmd.Run()
+		if err != nil {
+			return err
+		}
+
+		return nil
```
Comment (ahadas) [inline cmd/image-converter/image-converter.go:50]: if the don't have `return nil` in the block above, why having it here? I'd rather drop it (or add it to the block above and drop it below)

File: cmd/image-converter/image-converter.go [hunk 3]
```diff
@@ -57,21 +85,20 @@ func convert(srcVolPath, dstVolPath, sourceFormat, targetFormat string) error {
...
-	if err != nil {
-		return err
+	stat, ok := fileInfo.Sys().(*syscall.Stat_t)
+	if !ok {
+		klog.Fatal("failed to get raw syscall.Stat_t data")
 	}
 
-	return nil
+	// Check if it's a block device
+	return (stat.Mode & syscall.S_IFMT) == syscall.S_IFBLK
```
Comment (ahadas) [inline cmd/image-converter/image-converter.go:103]: what happens on rbd that supports both (when we get a filesystem on block storage)?

Comment (bennyz) [reply cmd/image-converter/image-converter.go:103]: it depends on the volumeMode on the PVC, which determines how it's attached to the node, so it shouldn't matter

File: cmd/image-converter/image-converter.go (hunk 2 above)
Comment (bennyz) [reply cmd/image-converter/image-converter.go:50]: bad copy paste...

File: cmd/image-converter/image-converter.go (hunk 3 above)
Comment (ahadas) [reply cmd/image-converter/image-converter.go:101]: ok, then (stat.Mode & syscall.S_IFMT) will return a filesystem in that case and both source and destination volumes are of the same mode so it looks correct, but why not to propagate this from the controller that knows the mode already?

File: cmd/image-converter/image-converter.go [hunk 4]
```diff
@@ -25,13 +27,37 @@ func main() {
...
+	}
+
+	// Copy dst over src
+	if isBlockDevice(srcVolPath) {
+		err = qemuimgConvert(dstVolPath, srcVolPath, dstFormat, dstFormat)
+		if err != nil {
+			return err
+		}
+	} else {
+		// Use mv for files as its faster than qemu-img convert
```
Comment (ahadas) [inline cmd/image-converter/image-converter.go:43]:
```suggestion
		// Use mv for files as it's faster than qemu-img convert
```

File: cmd/image-converter/image-converter.go (hunk 3 above)
Comment (bennyz) [reply cmd/image-converter/image-converter.go:101]: i think it's weird from the standpoint of the container to request something that can be determined

Comment (ahadas) [reply cmd/image-converter/image-converter.go]: yeah, it's less standalone but on the other hand it's simplify the code - I think it looks better now, thanks for changing that

**Review by ahadas — APPROVED** [review]
@bennyz I've added another commit to handle the case of `pvc.Spec.VolumeMode == nil` when setting the volume-mode parameter, please take a look at that change
