### PR TITLE
Set security context to v2v

### LINKED ISSUE #173: Conversion pod fails in restricted namespaces
When migrating to a namespace that is labeled with `pod-security.kubernetes.io/enforce=restricted`, the migration fails because the conversion pod cannot start there with the following error:
`pods "..." is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "vddk-side-car", "virt-v2v" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "vddk-side-car", "virt-v2v" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "vddk-side-car", "virt-v2v" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "vddk-side-car", "virt-v2v" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`
I'm going to drop that security label from namespaces that are created by our testing framework and this change would need to be reverted when fixing this issue

### PR DESCRIPTION
**Pull request by liranr23**
The v2v container needs security context in order to run in restricted namespaces.

### CODE REVIEW

File: pkg/controller/plan/kubevirt.go [hunk 1]
```diff
@@ -1265,6 +1276,14 @@ func (r *KubeVirt) guestConversionPod(vm *plan.VMStatus, vmVolumes []cnv.Volume,
 							Protocol:      core.ProtocolTCP,
 						},
 					},
+					SecurityContext: &core.SecurityContext{
+						AllowPrivilegeEscalation: &allowPrivilageEscalation,
+						RunAsNonRoot:             &nonRoot,
+						RunAsUser:                &fsGroup,
```
Comment (nyoxi) [inline pkg/controller/plan/kubevirt.go:1282]: Why is this needed and why to set UID from GID?

File: pkg/controller/plan/kubevirt.go [hunk 2]
```diff
@@ -1265,6 +1276,14 @@ func (r *KubeVirt) guestConversionPod(vm *plan.VMStatus, vmVolumes []cnv.Volume,
 							Protocol:      core.ProtocolTCP,
 						},
 					},
+					SecurityContext: &core.SecurityContext{
+						AllowPrivilegeEscalation: &allowPrivilageEscalation,
+						RunAsNonRoot:             &nonRoot,
```
Comment (nyoxi) [inline pkg/controller/plan/kubevirt.go:1281]: This can be moved to `Pod.SecurityContext` to avoid duplication.

**Review by nyoxi — CHANGES_REQUESTED** [review]
You are not setting and `SeccompProfile` (can be set in `Pod.SecurityContext`) and you should also define the context for the init container with VDDK.

File: pkg/controller/plan/kubevirt.go (hunk 1 above)
Comment (liranr23) [reply pkg/controller/plan/kubevirt.go:1290]: qemu is 107:107, so it's the same user and group

**Comment by liranr23** [comment]
> You are not setting `SeccompProfile` (can be set in `Pod.SecurityContext`) and you should also define the context for the init container with VDDK.

Please refer to https://github.com/kubev2v/forklift/pull/211

File: pkg/controller/plan/kubevirt.go (hunk 1 above)
Comment (nyoxi) [reply pkg/controller/plan/kubevirt.go:1290]: Sure but then we should be explicit about it and define `qemuUser` constant.

File: pkg/controller/plan/kubevirt.go (hunk 2 above)
Comment (nyoxi) [reply pkg/controller/plan/kubevirt.go:1289]: It worked for me, please re-check. The documentation states that:

>  May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.

File: pkg/controller/plan/kubevirt.go (hunk 1 above)
Comment (liranr23) [reply pkg/controller/plan/kubevirt.go:1290]: i did, just the naming within the function is wrong, i'll change.

**Comment by nyoxi** [comment]
> > You are not setting `SeccompProfile` (can be set in `Pod.SecurityContext`) and you should also define the context for the init container with VDDK.
> 
> Please refer to #211 for the `SeccompProfile`.

I wonder why I didn't have this issue.

> are you sure it's needed for the init container? it does pass the vsphere ci on restricted namespace.

Yes. If you look at the error provided in #173 it mentions both containers: `pod or containers "vddk-side-car", "virt-v2v" must set...`

File: pkg/controller/plan/kubevirt.go (hunk 2 above)
Comment (nyoxi) [reply pkg/controller/plan/kubevirt.go:1297]: Yes, I am not saying we don't. But we already have `PodSecurityContext` with some configuration so it makes sense to set the fields that can be set there instead of duplicating that per container.

File: pkg/controller/plan/kubevirt.go [hunk 3]
```diff
@@ -1224,7 +1244,7 @@ func (r *KubeVirt) guestConversionPod(vm *plan.VMStatus, vmVolumes []cnv.Volume,
 		},
 		Spec: core.PodSpec{
 			SecurityContext: &core.PodSecurityContext{
-				FSGroup: &fsGroup,
+				FSGroup: &qemuUser,
 			},
```
Comment (nyoxi) [inline pkg/controller/plan/kubevirt.go:1248]: You added `SeccompProfile` to the PVC binding Pod but forgot to add it to the conversion Pod.

File: pkg/controller/plan/kubevirt.go [hunk 4]
```diff
@@ -1202,7 +1220,9 @@ func (r *KubeVirt) guestConversionPod(vm *plan.VMStatus, vmVolumes []cnv.Volume,
 	}
 
 	// qemu group
-	fsGroup := int64(107)
+	qemuUser := int64(qemuGroup)
```
Comment (nyoxi) [inline pkg/controller/plan/kubevirt.go:1223]: That did not came out the way I have imagined it. :) Could we have two constants `qemuUser` and `qemuGroup` to avoid this confusing assignments? That way it will be clear that those have same value on purpose (not by coincidence) and it's not a bug or a some hack. Here you would have `fsGroup := qemuGroup` then.

**Review by nyoxi — CHANGES_REQUESTED** [review]

File: pkg/controller/plan/kubevirt.go (hunk 4 above)
Comment (liranr23) [reply pkg/controller/plan/kubevirt.go:1223]: unfortunately i must assign it. it's problematic to use const as pointer.
and yes, i will do 2 consts with 107 and just assign here..

File: pkg/controller/plan/kubevirt.go (hunk 3 above)
Comment (liranr23) [reply pkg/controller/plan/kubevirt.go:1248]: i really don't like the mixup of `SeccompProfile` when setting user ID. let's not add it.

**Review by ahadas — APPROVED** [review]
